### ISSUE TITLE
End primitive

### ISSUE THREAD

**Issue by JordyvanDortmont** [ideas-edu/ideas#1]
The succeed and fail primitives seem to be insufficient for describing certain strategies that end after a certain rule or strategy.
The introduction of an end primitive would solve this problem. In the below example the need of such a primitive is shown and motivated.

`(a .*. ((b .*. end) .|. c)) .*. d`

When we choose "a", we expect "b" or "c" to follow and when we choose "c" after "a", we expect "d", but when we choose "b", we expect succeed without sequencing "d" after, because of end.

However currently we cannot define end in terms of succeed and fail, because `succeed .*. d = d` and `fail .*. d = fail`, which is also not what we want.

Also defining end as a high-level combinator will lead to a split in the strategy to the point where it is no longer left-factorised. For the above example we would get:

`(a .*. b .*. end) .|. (a .*. c .*. d)`

This is less efficient and can be avoided by introducing end as a primitive.

**Comment by alexgerdes** [comment]
I don't see the need. The strategy you want can be described as follows:

`a .*. (b .|. c .*. d)`

**Comment by BastiaanHeeren** [comment]
The idea of the 'end' combinator is that a sequence 'successfullly' ends at that point. This is best seen in its interaction with the sequence combinator:

```
succeed .*. s = s
fail .*. s = fail
end .*. s = end
```

The difference between fail and end is how they finish (i.e. the empty/ready property), which is success (like succeed) for the latter.

If you have the complete strategy, you can rewrite a strategy with the end combinator into a strategy without that combinator. However, this is not possible if the strategy is used in a composition (with other strategies).

I am not sure yet how to best implement the end combinator: it could perhaps be implemented as a special symbol, or else turned into a primitive combinator.

**Comment by mvangeest** [comment]
Your succinct characterisation of end, "[End is just like fail.] The difference between fail and end is how they finish (i.e. the empty/ready property)", implies that end is only necessary for a client if that client cares about the ready property. Communicate doesn't use the ready property, so we shouldn't really need end.

Several bugs involving fail and interleaving (#5 and #9) led us to believe that fail was insufficient for us. Those bugs have recently been fixed, and we have successfully implemented our "ending" strategies using fail with the master version of Ideas. That means we currently don't need end (and we predict we won't be using ready in the foreseeable future). We think this proposal is still completely valid, but we wouldn't mind it being shelved until someone needs this feature.
