### ISSUE TITLE
Typos in Tutorial on site

### ISSUE THREAD

**Issue by alogic0** [ideas-edu/ideas#25]
Hi! I've found some typos or artifacts on the [site version](http://ideas.cs.uu.nl/tutorial/) of the Tutorial. 

1.  The first argument is the **ruleâ€™s** identifier
2.  The MakeTrans type class that is part of **makeRuleâ€™s** type
3.  Step 2: adding **traverals**
4.  calculating with fractions **(e.g.Â** 5/7 
5.  mixed fractions **(e.g.Â** 17/14

**Comment by BastiaanHeeren** [comment]
Thanks for reporting: these issues have been fixed.
