### ISSUE TITLE
Text encoding (UTF-8) asymmetry

### ISSUE THREAD

**Issue by mvangeest** [ideas-edu/ideas#3]
Some time ago, the Communicate team discovered an annoying asymmetry between how input and output is encoded by the `cgi` library. Specifically, _input_ is decoded from UTF-8 to a list of Unicode code units (i.e. a "real" `String`), while output is not touched. This means that it is possible for a client using Ideas to receive a character, send it back unchanged, and get a decoding exception (if the character is not also encoded as an XML entity or JSON escape sequence).

It turns out that this behaviour is **not** intentional, but caused by an unannounced change in the behaviour of `network`. See cheecheeo/haskell-cgi#23 for the full discussion. The `cgi` maintainer has released a new version (3001.3.0.0) that corrects this behaviour (by touching neither the input nor the output).

`cgi` was imported into the Ideas tree in commit a25385d5d9f076d2ea9ca3f33ca5a9bf5c967b28 in order to fix a dependency problem involving `mtl`. This problem was solved in cheecheeo/haskell-cgi@46a6cb8761103f112f46f5c9345f549c130470ff. Whether it's a good idea to remove `cgi` from the tree and use the latest version depends on whether support for GHC 7.8 and older **will be dropped**:
- If Ideas will only support GHC 7.10 and up from now on, the cleanest solution is to remove `cgi` from the tree and add a dependency on `cgi >= 3001.3.0.0`.
- If Ideas still wants to support GHC 7.8 and older, doing the above is possible, but will make life harder for Windows users. There's no Haskell Platform that contains both GHC 7.8 and `time-1.5`, a version `cgi-3001.3.0.0` depends on, and `time` is hard to build on Windows. In this case, I recommend applying cheecheeo/haskell-cgi@42f4ca7 to the in-tree `cgi`.

Note that in the current state of the master branch, Ideas does not support GHC 7.8 or older, because refers to `Applicative` without importing `Control.Applicative`. I don't know if this is intentional or not.

**Comment by BastiaanHeeren** [comment]
Support for ghc 7.8 (and older) will be dropped (for the next release): there are too many incompatibilities. The ideas virtual server is already upgraded to ghc 7.10.
