### ISSUE TITLE
XML unescaping issue

### ISSUE THREAD

**Issue by nsbgn** [ideas-edu/ideas#35]
Currently, escaped characters are unescaped after parsing XML. This leads to issues: notably, `"<x>y&lt;</x>"` will be parsed as `<x>y<</x>`, which, when printed again, leads to invalid XML (see `Ideas.Text.XML.parseXML`).

**Comment by nsbgn** [comment]
As a quick workaround, one could transform all instances of "&" to "&amp;amp;" prior to parsing, which in a practical sense is the same as not unescaping at all. As for a more permanent fix, I don't think that skipping the unescaping step is viable: escape codes are used precisely so that the parser can unescape them. (The presence of the `unescaped` function would also suggest that this is not the intended behaviour).

Instead, escape sequences may be unescaped as now, but when printing, all [five](https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents) characters that are relevant according to the [standard](https://www.w3.org/TR/xml/#syntax) should be (re-)escaped. Short of using a third-party library, this seems most correct. However, it transforms user data, opening up questions like: which characters are unescaped and which aren't? Should there be a difference between `<x>&#x61;</x>` and `<x>a</x>`? I'm inclined to think that we cannot expect a law like `parse . show . parse == id` to hold anyway, so we have freedom on this front, but I'm not familiar enough with the XML standard to be certain. I can imagine that escaping functionality and quirks are used as a feature in code that depends on Ideas. Are there any foreseeable issues if this path is chosen? For example, what if someone `(Right xml) = parseXML "<x>\"y\"</x>"` and expects `getData xml == "\"y\""` when in fact `getData xml == "&quot;y&quot;"`?

Deferring these worries to a third-party library would be ideal, but that is probably not viable in the short term. I would suggest to solve the immediate issue in the way outlined above, but keep these possible problems in mind.

**Comment by BastiaanHeeren** [comment]
https://github.com/ideas-edu/ideas/pull/42
